// <auto-generated />
using Inception.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Inception.Repository.Migrations
{
    [DbContext(typeof(InceptionDbContext))]
    partial class InceptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inception.Repository.Testing.LinkTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ResponseTime");

                    b.Property<int>("SiteTestResultId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("SiteTestResultId");

                    b.ToTable("LinkTestResults");
                });

            modelBuilder.Entity("Inception.Repository.Testing.Overview.LinkTestOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaximumResponseTime");

                    b.Property<int>("MinimumResponseTime");

                    b.Property<int>("SiteTestOverviewId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("SiteTestOverviewId");

                    b.ToTable("LinkTestOverviews");
                });

            modelBuilder.Entity("Inception.Repository.Testing.Overview.SiteTestOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FirstTestedOn");

                    b.Property<DateTime>("LastTestedOn");

                    b.HasKey("Id");

                    b.ToTable("SiteTestOverviews");
                });

            modelBuilder.Entity("Inception.Repository.Testing.SiteTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DomainName");

                    b.Property<DateTime>("TestedOn");

                    b.HasKey("Id");

                    b.ToTable("SiteTestResults");
                });

            modelBuilder.Entity("Inception.Repository.Testing.LinkTestResult", b =>
                {
                    b.HasOne("Inception.Repository.Testing.SiteTestResult", "SiteTestResult")
                        .WithMany("LinkTestResults")
                        .HasForeignKey("SiteTestResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Inception.Repository.Testing.Overview.LinkTestOverview", b =>
                {
                    b.HasOne("Inception.Repository.Testing.Overview.SiteTestOverview", "SiteTestOverview")
                        .WithMany("LinkTestOverviews")
                        .HasForeignKey("SiteTestOverviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
